<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-06 19:10
=======
# Generated by Django 4.2.7 on 2023-12-07 10:49
>>>>>>> 242ae53128cdb93b4a04daa5eab8f623cf9e55e7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('CIN', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('presence', models.BooleanField()),
=======
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('CIN', models.CharField(max_length=100)),
                ('telephone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('presence', models.BooleanField(default=False)),
>>>>>>> 242ae53128cdb93b4a04daa5eab8f623cf9e55e7
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
