# Generated by Django 4.2.1 on 2023-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='name',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='email',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
