# Generated by Django 5.0.2 on 2024-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
