# Generated by Django 4.2.7 on 2023-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='CIN',
            field=models.CharField(default='', max_length=100),
        ),
    ]
