# Generated by Django 4.2.1 on 2023-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_rename_name_rendezvous_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='patient',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='notes',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
