# Generated by Django 4.2.7 on 2023-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_rendezvous_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='CIN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
