# Generated by Django 4.2.1 on 2023-08-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_patient_rendezvous_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
