# Generated by Django 4.2.1 on 2023-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_rendezvous_prenom_rendezvous_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
